float e_intra_score (int,int) ;
float e_inter_score (int,int) ;



affine bpmax 
{
	M, N, N_sec, N_tile, MR, NR | 
	M >= 3 &&  N >= 8 &&  N_sec >= 2 && N_tile >=4 && MR >=1 && NR>=1
}
input
	int seq2 {i| 0 <= i < N} ;
output
	float S2 {i,j| 0 <= i <= j < N };
let
	S2[i,j] = case
		{ | j-i<= 3}: 0 ;
		{ | j-i > 3}: max (S2[i+1,j-1] + e_intra_score (seq2[N-i-1],seq2[N-j-1]),
					  reduce(max, [k], {| k<j}:S2[i,k]+S2[k+1,j]));
			esac;
.




